from __future__ import annotations

from math import erf, sqrt
from typing import Literal

import numpy as np

OptionKind = Literal["call", "put"]


def black_scholes_price(
    kind: OptionKind,
    spot: float | np.ndarray,
    strike: float | np.ndarray,
    time_to_expiry: float | np.ndarray,
    risk_free_rate: float,
    volatility: float | np.ndarray,
    dividend_yield: float = 0.0,
) -> float | np.ndarray:
    """Price a European call or put under the Black-Scholes-Merton model."""

    kind = _normalize_kind(kind)
    spot, strike, time_to_expiry, volatility = _validated_arrays(
        spot, strike, time_to_expiry, volatility
    )
    d1, d2 = _d1_d2(
        spot=spot,
        strike=strike,
        time_to_expiry=time_to_expiry,
        risk_free_rate=risk_free_rate,
        volatility=volatility,
        dividend_yield=dividend_yield,
    )

    discounted_spot = spot * np.exp(-dividend_yield * time_to_expiry)
    discounted_strike = strike * np.exp(-risk_free_rate * time_to_expiry)

    if kind == "call":
        price = discounted_spot * _normal_cdf(d1) - discounted_strike * _normal_cdf(d2)
    else:
        price = discounted_strike * _normal_cdf(-d2) - discounted_spot * _normal_cdf(-d1)

    return _maybe_scalar(price)


def black_scholes_greeks(
    kind: OptionKind,
    spot: float,
    strike: float,
    time_to_expiry: float,
    risk_free_rate: float,
    volatility: float,
    dividend_yield: float = 0.0,
) -> dict[str, float]:
    """Return Delta, Gamma, Vega, Theta, and Rho for a European option."""

    kind = _normalize_kind(kind)
    spot_array, strike_array, time_array, vol_array = _validated_arrays(
        spot, strike, time_to_expiry, volatility
    )
    d1, d2 = _d1_d2(
        spot=spot_array,
        strike=strike_array,
        time_to_expiry=time_array,
        risk_free_rate=risk_free_rate,
        volatility=vol_array,
        dividend_yield=dividend_yield,
    )

    pdf_d1 = _normal_pdf(d1)
    discount_q = np.exp(-dividend_yield * time_array)
    discount_r = np.exp(-risk_free_rate * time_array)
    sqrt_t = np.sqrt(time_array)

    gamma = discount_q * pdf_d1 / (spot_array * vol_array * sqrt_t)
    vega = spot_array * discount_q * pdf_d1 * sqrt_t
    shared_theta = -(spot_array * discount_q * pdf_d1 * vol_array) / (2.0 * sqrt_t)

    if kind == "call":
        delta = discount_q * _normal_cdf(d1)
        theta = (
            shared_theta
            - risk_free_rate * strike_array * discount_r * _normal_cdf(d2)
            + dividend_yield * spot_array * discount_q * _normal_cdf(d1)
        )
        rho = strike_array * time_array * discount_r * _normal_cdf(d2)
    else:
        delta = discount_q * (_normal_cdf(d1) - 1.0)
        theta = (
            shared_theta
            + risk_free_rate * strike_array * discount_r * _normal_cdf(-d2)
            - dividend_yield * spot_array * discount_q * _normal_cdf(-d1)
        )
        rho = -strike_array * time_array * discount_r * _normal_cdf(-d2)

    return {
        "delta": float(delta),
        "gamma": float(gamma),
        "vega": float(vega),
        "theta": float(theta),
        "rho": float(rho),
    }


def implied_volatility(
    kind: OptionKind,
    market_price: float,
    spot: float,
    strike: float,
    time_to_expiry: float,
    risk_free_rate: float,
    dividend_yield: float = 0.0,
    lower: float = 1e-6,
    upper: float = 5.0,
    tolerance: float = 1e-8,
    max_iterations: int = 100,
) -> float:
    """Invert Black-Scholes price with a bracketed bisection solver."""

    kind = _normalize_kind(kind)
    if market_price <= 0:
        raise ValueError("market_price must be positive.")
    if lower <= 0 or upper <= lower:
        raise ValueError("Require 0 < lower < upper for volatility bounds.")

    low_price = black_scholes_price(
        kind,
        spot,
        strike,
        time_to_expiry,
        risk_free_rate,
        lower,
        dividend_yield,
    )
    high_price = black_scholes_price(
        kind,
        spot,
        strike,
        time_to_expiry,
        risk_free_rate,
        upper,
        dividend_yield,
    )
    if market_price < low_price - tolerance or market_price > high_price + tolerance:
        raise ValueError(
            "market_price is outside the prices generated by the volatility bracket."
        )

    low = lower
    high = upper
    mid = (low + high) / 2.0

    for _ in range(max_iterations):
        mid = (low + high) / 2.0
        model_price = black_scholes_price(
            kind,
            spot,
            strike,
            time_to_expiry,
            risk_free_rate,
            mid,
            dividend_yield,
        )
        error = model_price - market_price
        if abs(error) <= tolerance:
            return mid
        if error > 0:
            high = mid
        else:
            low = mid

    return mid


def _d1_d2(
    spot: np.ndarray,
    strike: np.ndarray,
    time_to_expiry: np.ndarray,
    risk_free_rate: float,
    volatility: np.ndarray,
    dividend_yield: float,
) -> tuple[np.ndarray, np.ndarray]:
    sqrt_t = np.sqrt(time_to_expiry)
    numerator = np.log(spot / strike) + (
        risk_free_rate - dividend_yield + 0.5 * volatility**2
    ) * time_to_expiry
    denominator = volatility * sqrt_t
    d1 = numerator / denominator
    d2 = d1 - denominator
    return d1, d2


def _normal_cdf(value: float | np.ndarray) -> np.ndarray:
    value = np.asarray(value, dtype=float)
    erf_vectorized = np.vectorize(erf, otypes=[float])
    return 0.5 * (1.0 + erf_vectorized(value / sqrt(2.0)))


def _normal_pdf(value: float | np.ndarray) -> np.ndarray:
    value = np.asarray(value, dtype=float)
    return np.exp(-0.5 * value**2) / sqrt(2.0 * np.pi)


def _validated_arrays(
    spot: float | np.ndarray,
    strike: float | np.ndarray,
    time_to_expiry: float | np.ndarray,
    volatility: float | np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    arrays = tuple(np.asarray(value, dtype=float) for value in (spot, strike, time_to_expiry, volatility))
    labels = ("spot", "strike", "time_to_expiry", "volatility")
    for label, array in zip(labels, arrays, strict=True):
        if np.any(array <= 0):
            raise ValueError(f"{label} must be strictly positive.")
    return arrays


def _normalize_kind(kind: str) -> OptionKind:
    normalized = kind.lower().strip()
    if normalized not in {"call", "put"}:
        raise ValueError("kind must be 'call' or 'put'.")
    return normalized  # type: ignore[return-value]


def _maybe_scalar(value: np.ndarray) -> float | np.ndarray:
    if value.ndim == 0:
        return float(value)
    return value
